{\rtf1\ansi\ansicpg1252\cocoartf2636
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww27960\viewh16380\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs36 \cf0 git:\
    filters:\
      - filter_type: file\
        # all supported i18n types: https://docs.transifex.com/formats\
        file_format: PO\
        source_language: en\
        source_file: SourceFiles/example.po\
        # path expression to translation files, must contain <lang> placeholder\
        translation_files_expression: 'Translations/<lang>/'\
\
      - filter_type: dir\
        file_format: KEYVALUEJSON\
        source_file_extension: json\
        source_language: en\
        source_file_dir: SourceFiles\
        translation_files_expression: 'Translations/<lang>/'\
}