git:
    filters:
      - filter_type: file
        # all supported i18n types: https://docs.transifex.com/formats
        file_format: PO
        source_language: en
        ource_file: SourceFiles/example.po
        # path expression to translation files, must contain <lang> placeholder
        translation_files_expression: 'Translations/<lang>/'